version: '3.8'
services:
  postgres:
    container_name: kata-jpa-postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kata
    ports:
      - "5432:5432"

  pgadmin:
    container_name: kata-jpa-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "5050:80"