spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kata
    username: admin
    password: pass
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true


